apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
  EMAIL_HOST_USER: {{ .Values.email.user | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.email.password | quote }}
  REPORT_RECIPIENT_EMAIL: {{ .Values.email.to | quote }}
