apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
