# Generated by Django 6.0.2 on 2026-02-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('portfolio', '0002_ticker_avg_volume_ticker_day_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=8)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='portfolio.ticker')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('ticker', 'url')},
            },
        ),
    ]
