# Generated by Django 6.0.2 on 2026-04-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rss_feeds'),
        ('portfolio', '0008_make_user_fields_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end_date', models.DateField()),
                ('fiscal_period', models.CharField(max_length=10)),
                ('eps_actual', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('growth_yoy_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_earnings', to='portfolio.ticker')),
            ],
            options={
                'ordering': ['-period_end_date'],
                'unique_together': {('ticker', 'period_end_date')},
            },
        ),
    ]
