# Generated by Django 6.0.2 on 2026-04-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_quarterlyearning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarterlyearning',
            old_name='growth_yoy_pct',
            new_name='growth_qoq_pct',
        ),
    ]
