# Generated by Django 6.0.2 on 2026-02-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_ticker_avg_volume_ticker_day_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rsi_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_signal_line', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sma_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('volume_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('opportunity_score', models.IntegerField(default=50)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='portfolio.ticker')),
            ],
            options={
                'ordering': ['-opportunity_score'],
            },
        ),
    ]
