# Generated by Django 6.0.2 on 2026-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsnapshot',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='indicatorsnapshot',
            name='sentiment_signal',
            field=models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4),
        ),
    ]
