# Generated by Django 6.0.2 on 2026-02-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_indicatorsnapshot_sentiment_score_and_more'),
        ('portfolio', '0003_watchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('model_name', models.CharField(default='llama3.2:1b', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='portfolio.ticker')),
            ],
            options={
                'verbose_name_plural': 'AI analyses',
            },
        ),
    ]
