# Generated by Django 6.0.2 on 2026-03-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_aianalysis'),
        ('portfolio', '0005_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_call_volume_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('put_call_oi_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('iv_skew', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('max_pain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_unusual_activity', models.BooleanField(default=False)),
                ('unusual_activity_details', models.JSONField(blank=True, default=list)),
                ('expirations_analyzed', models.JSONField(blank=True, default=list)),
                ('options_signal', models.CharField(choices=[('buy', 'Buy'), ('hold', 'Hold'), ('sell', 'Sell')], default='hold', max_length=4)),
                ('options_score', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options_snapshot', to='portfolio.ticker')),
            ],
            options={
                'ordering': ['-options_score'],
            },
        ),
    ]
