# Generated by Django 6.0.2 on 2026-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_options_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsnapshot',
            name='buy_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='indicatorsnapshot',
            name='sell_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
