# Generated by Django 6.0.2 on 2026-03-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_price_targets'),
        ('portfolio', '0005_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_picks_text', models.TextField(blank=True)),
                ('top_pick_symbols', models.JSONField(blank=True, default=list)),
                ('portfolio_analysis_text', models.TextField(blank=True)),
                ('model_name', models.CharField(default='llama3.2:1b', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=64)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_portfolio_analysis', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio analyses',
            },
        ),
    ]
