# Generated by Django 6.0.2 on 2026-03-29 01:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_portfolio_analysis'),
        ('portfolio', '0008_make_user_fields_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIKMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cik_mapping', to='portfolio.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='SECFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=20)),
                ('filed_at', models.DateTimeField()),
                ('filer_name', models.CharField(max_length=300)),
                ('filer_title', models.CharField(blank=True, max_length=200)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('exercise', 'Exercise'), ('acquisition', 'Acquisition'), ('disposition', 'Disposition')], max_length=15)),
                ('shares', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('ownership_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('accession_number', models.CharField(max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_filings', to='portfolio.ticker')),
            ],
            options={
                'ordering': ['-filed_at'],
                'unique_together': {('ticker', 'accession_number')},
            },
        ),
        migrations.CreateModel(
            name='WhaleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('signal', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('confidence', models.IntegerField(default=0)),
                ('insider_buy_count', models.IntegerField(default=0)),
                ('insider_sell_count', models.IntegerField(default=0)),
                ('insider_net_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('institutional_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_13d_filing', models.BooleanField(default=False)),
                ('options_volume_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('oi_change_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('block_trade_detected', models.BooleanField(default=False)),
                ('volume_price_divergence', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whale_activities', to='portfolio.ticker')),
            ],
            options={
                'verbose_name_plural': 'Whale activities',
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
