# Generated by Django 6.0.2 on 2026-03-28 20:01

from django.db import migrations


def assign_to_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Portfolio = apps.get_model('portfolio', 'Portfolio')
    ReportSchedule = apps.get_model('portfolio', 'ReportSchedule')
    WatchlistItem = apps.get_model('portfolio', 'WatchlistItem')

    superuser = User.objects.filter(is_superuser=True).first()
    if superuser is None:
        # If no superuser exists, use the first user
        superuser = User.objects.first()
    if superuser is None:
        return  # No users at all, nothing to migrate

    Portfolio.objects.filter(user__isnull=True).update(user=superuser)
    ReportSchedule.objects.filter(user__isnull=True).update(user=superuser)
    WatchlistItem.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_user_fields_nullable'),
    ]

    operations = [
        migrations.RunPython(assign_to_superuser, migrations.RunPython.noop),
    ]
